### ISSUE TITLE
ERR_INVALID_ARG_TYPE: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by nachtfunke** [maoberlehner/node-sass-magic-importer#198]
Hello!

I have found a few already resolved issues for this specific error, but they do not fix our problem unfortunately.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at Object.importer (/Users/path/packages/sass/node_modules/node-sass-magic-importer/dist/index.js:58:38)
    at options.importer (/Users/path/packages/sass/node_modules/node-sass/lib/index.js:336:31)
```

For some weird reason, all of this works without a problem on my machine, but fails on my colleague's machine. Is this maybe related to a specific Node Version?

**Comment by maoberlehner** [comment]
Could be Node version related, could be OS related, could be a bug. Hard to say without further information.

**Comment by maoberlehner** [comment]
Closing this in favor of re-opening: https://github.com/maoberlehner/node-sass-magic-importer/issues/187
