### ISSUE TITLE
Import issue when trying to import a non existing file with ~ notation

### ISSUE THREAD

**Issue by lordgiotto** [maoberlehner/node-sass-magic-importer#93]
Hi again, sorry for bothering you 😅

I've noticed another small issue with the version you just released.

If I try to import a file that not exists with the ~ notation, (for instance `@import "~bootstrap-sass/assets/stylesheets/bootstrap/wrong-file-name";`) this error occurs:

```
file = file.replace(/\.css$/, "");
             ^

TypeError: Cannot read property 'replace' of null
    at PackageImporter.resolveSync (/Users/name/project/node_modules/node-sass-package-importer/dist/PackageImporter.js:82:14)
    at MagicImporter.resolveSync (/Users/name/project/node_modules/node-sass-magic-importer/dist/index.js:173:47)
    at Object.importer (/Users/name/project/node_modules/node-sass-magic-importer/dist/index.js:271:26)
    at options.importer.(anonymous function) (/Users/name/project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:323:32)
```

**Comment by maoberlehner** [comment]
Oh, wow – this slipped through  the tests. Fixed now.
Thanks for reporting.
